server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:panshenghuai/springcloud-config.git #仓库名字
          search-paths:
            - springcloud-config #搜索目录
      label: master
eureka:
  instance:
    instance-id: config-center
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/