server:
  port: 8001
#spring的配置
spring:
  application:
    #微服务名称
    name: cloud-payment-server
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.132:3306/springcloud?serverTimezone=UTC
    username: root
    password: yesido095
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.my.cloud.entities
  configuration:
    map-underscore-to-camel-case: true
#eureka配置
eureka:
  client:
    #表示注册进EurekaSer，默认为true
    register-with-eureka: true
    #是否从eureka server 抓取已有的注册信息，默认为true单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机版
      #defaultZone: http://localhost:7001/eureka/
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  #主机名称
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    #客户端向服务端发送心跳的时间间隔，单位秒，默认时间是30
    lease-renewal-interval-in-seconds: 30
    #服务端在最后一次收到客户端心跳后的等待上限，默认时间是90秒，超时将剔除
    lease-expiration-duration-in-seconds: 90