server:
  port: 9527
spring:
  application:
    name: cloud-gateway-client
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment-gateway-get #路由的id，没有固定规则但要求唯一
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVER
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头上加上一对请求头，名称为X-Request-Id，值为1024
          predicates:
            - Path=/payment/get/** #断言，路径匹配的进行路由
            - Method=GET,POST

eureka:
  instance:
    instance-id: gateway9527
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/