server:
  port: 8005
spring:
  application:
    name: cloud-provider-consul-payment
  cloud:
    consul:
      host: http://192.168.200.132
      port: 8500
      discovery:
        service-name: ${spring.application.name}