server:
  port: 8004
spring:
  application:
    name: cloud-zookeeper-server
  cloud:
    zookeeper:
      connect-string: 192.168.200.132:2181
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.132:3306/springcloud?serverTimezone=UTC
    username: root
    password: yesido095
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.my.cloud.entities
  configuration:
    map-underscore-to-camel-case: true