server:
  port: 80
spring:
  application:
    name: cloud-comsumer-consul-order
  cloud:
    consul:
      host: http://192.168.200.132
      port: 8500
      discovery:
        service-name: ${spring.application.name}